import type { User, Gig, Application } from './types'

export const streamers: User[] = [
  {
    id: 's1',
    name: 'LunaRae',
    handle: 'lunarae',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=lunarae',
    role: 'streamer',
    bio: 'variety streamer | FPS queen | 25k hours in Fortnite | collab-friendly',
    joinedAt: '2023-08-14T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: 420,
    followers: 12800,
    totalGigsCompleted: 12,
    rating: 4.8,
    vibeScore: 92,
  },
  {
    id: 's2',
    name: 'Hexical',
    handle: 'hexytv',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=hexical',
    role: 'streamer',
    bio: 'Minecraft parkour god & indie game enjoyer. Building a community one block at a time.',
    joinedAt: '2024-01-22T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: 180,
    followers: 5500,
    totalGigsCompleted: 8,
    rating: 4.5,
    vibeScore: 78,
  },
  {
    id: 's3',
    name: 'KaiZen',
    handle: 'kaizentv',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=kaizen',
    role: 'streamer',
    bio: 'Roblox UGC reviewer & fashion guru. I find the dopest cosmetics so you dont have to.',
    joinedAt: '2024-03-10T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: 320,
    followers: 8900,
    totalGigsCompleted: 15,
    rating: 4.9,
    vibeScore: 95,
  },
  {
    id: 's4',
    name: 'PixelKitten',
    handle: 'pixelkitten',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=pixelkitten',
    role: 'streamer',
    bio: 'wholesome variety streamer | cozy games | FPS when the mood hits | 18+ chat',
    joinedAt: '2023-11-05T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: 250,
    followers: 7200,
    totalGigsCompleted: 6,
    rating: 4.6,
    vibeScore: 85,
  },
  {
    id: 's5',
    name: 'Vexxus',
    handle: 'vexxustv',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=vexxus',
    role: 'streamer',
    bio: 'Fortnite competitive grinder. Zone wars every day. Creative map tester.',
    joinedAt: '2024-05-18T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: 560,
    followers: 15400,
    totalGigsCompleted: 9,
    rating: 4.7,
    vibeScore: 88,
  },
  {
    id: 's6',
    name: 'MellowMorph',
    handle: 'mellowmorph',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=mellowmorph',
    role: 'streamer',
    bio: 'Late night vibes. Indie horror, puzzle games, and really bad puns.',
    joinedAt: '2024-02-14T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: 145,
    followers: 3800,
    totalGigsCompleted: 4,
    rating: 4.3,
    vibeScore: 72,
  },
  {
    id: 's7',
    name: 'ByteBae',
    handle: 'bytebae',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=bytebae',
    role: 'streamer',
    bio: 'tech + gaming | modded Minecraft | building insane redstone contraptions',
    joinedAt: '2023-09-30T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: 380,
    followers: 10200,
    totalGigsCompleted: 11,
    rating: 4.8,
    vibeScore: 90,
  },
  {
    id: 's8',
    name: 'DriftKing',
    handle: 'driftkingtv',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=driftking',
    role: 'streamer',
    bio: 'Fortnite box fighting phenom. Also speedrun any game you throw at me.',
    joinedAt: '2024-06-01T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: 220,
    followers: 6400,
    totalGigsCompleted: 5,
    rating: 4.4,
    vibeScore: 76,
  },
  {
    id: 's9',
    name: 'NovaGlow',
    handle: 'novaglow',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=novaglow',
    role: 'streamer',
    bio: 'art streamer | cozy game dev | I play my own games live | SUPPORT INDIE',
    joinedAt: '2024-04-12T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: 190,
    followers: 5100,
    totalGigsCompleted: 7,
    rating: 4.7,
    vibeScore: 83,
  },
  {
    id: 's10',
    name: 'TurboShark',
    handle: 'turboshark',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=turboshark',
    role: 'streamer',
    bio: 'I play literally anything. 1k hours in Roblox. Minecraft speedrunner. Bring it.',
    joinedAt: '2024-07-20T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: 310,
    followers: 8700,
    totalGigsCompleted: 3,
    rating: 4.2,
    vibeScore: 80,
  },
]

export const devs: User[] = [
  {
    id: 'd1',
    name: 'NeonForge',
    handle: 'neonforge',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=neonforge',
    role: 'dev',
    bio: 'indie game studio making weird & wonderful Steam games. 3 titles shipping this year.',
    joinedAt: '2024-01-08T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: true,
    totalGigsCompleted: 18,
    rating: 4.9,
    vibeScore: 94,
  },
  {
    id: 'd2',
    name: 'PixelPunch',
    handle: 'pixelpunch',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=pixelpunch',
    role: 'dev',
    bio: 'Fortnite Creative map designer. 12 published maps, 50M+ total plays.',
    joinedAt: '2024-02-19T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: false,
    totalGigsCompleted: 24,
    rating: 4.7,
    vibeScore: 89,
  },
  {
    id: 'd3',
    name: 'BlockSmith',
    handle: 'blocksmith',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=blocksmith',
    role: 'dev',
    bio: 'Minecraft server owner & plugin dev. Survival, minigames, and custom content.',
    joinedAt: '2024-03-05T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: false,
    totalGigsCompleted: 9,
    rating: 4.5,
    vibeScore: 81,
  },
  {
    id: 'd4',
    name: 'UGC Studios',
    handle: 'ugcstudios',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=ugcstudios',
    role: 'dev',
    bio: 'Roblox UGC creators. Limiteds, faces, accessories — if it looks fire, we made it.',
    joinedAt: '2024-04-01T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: true,
    totalGigsCompleted: 31,
    rating: 4.6,
    vibeScore: 87,
  },
  {
    id: 'd5',
    name: 'CrystalCode',
    handle: 'crystalcode',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=crystalcode',
    role: 'dev',
    bio: 'Solo dev. My game PNEUMA is coming to Steam Fall 2026. Body horror meets platformer.',
    joinedAt: '2024-06-15T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: true,
    totalGigsCompleted: 4,
    rating: 4.4,
    vibeScore: 79,
  },
  {
    id: 'd6',
    name: 'ForgeFrame',
    handle: 'forgeframe',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=forgeframe',
    role: 'dev',
    bio: 'Marketing agency for indie games. We connect devs with the right streamers.',
    joinedAt: '2023-12-10T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: true,
    totalGigsCompleted: 47,
    rating: 4.8,
    vibeScore: 92,
  },
  {
    id: 'd7',
    name: 'RiftLabs',
    handle: 'riftlabs',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=riftlabs',
    role: 'dev',
    bio: 'We build Roblox experiences. 200M+ visits across our 7 games.',
    joinedAt: '2024-05-22T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: false,
    totalGigsCompleted: 14,
    rating: 4.3,
    vibeScore: 77,
  },
  {
    id: 'd8',
    name: 'VoidInteractive',
    handle: 'voidinteractive',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=voidinteractive',
    role: 'dev',
    bio: 'Horror game studio. DARKWOOD and HOLLOW VESSEL out now on Steam.',
    joinedAt: '2024-01-30T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: true,
    totalGigsCompleted: 11,
    rating: 4.9,
    vibeScore: 96,
  },
  {
    id: 'd9',
    name: 'MojitoGames',
    handle: 'mojitogames',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=mojitogames',
    role: 'dev',
    bio: 'Casual mobile & PC dev. Making colorful games with deep mechanics.',
    joinedAt: '2024-07-01T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: false,
    totalGigsCompleted: 6,
    rating: 4.1,
    vibeScore: 73,
  },
  {
    id: 'd10',
    name: 'PhantomSeed',
    handle: 'phantomseed',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=phantomseed',
    role: 'dev',
    bio: 'Upcoming tactical roguelike ROGUE FREQUENCY. Seeking variety streamers for launch.',
    joinedAt: '2024-08-10T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: true,
    totalGigsCompleted: 2,
    rating: 4.0,
    vibeScore: 70,
  },
]

export const gigs: Gig[] = [
  {
    id: 'g1',
    devId: 'd2',
    devName: 'PixelPunch',
    devAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=pixelpunch',
    title: 'Playtest & Showcase Neon Rooftops FFA Map',
    description:
      "I just dropped Neon Rooftops — a 32-player free-for-all map with wall-running, ziplines, and neon-glazed POIs. Need a streamer to run it for 2 hours, show off the movement mechanics, and give honest feedback. Bonus if you clip the best moments for TikTok.",
    game: 'Fortnite (Creative)',
    gameType: 'fortnite',
    platform: 'twitch',
    budget: 150,
    payoutType: 'fixed',
    minFollowers: 1000,
    minAvgViewers: 50,
    duration: '2 hours',
    scheduledDate: '2026-06-10T18:00:00Z',
    status: 'open',
    tags: ['creative', 'ffa', 'new-map', 'gameplay'],
    applicants: 4,
    createdAt: '2026-05-19T10:00:00Z',
  },
  {
    id: 'g2',
    devId: 'd4',
    devName: 'UGC Studios',
    devAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=ugcstudios',
    title: 'Rate Our New Roblox Limited Face Collection',
    description:
      'Dropping 10 new limited faces next week. Want a streamer to go through them live, rate them, and style outfits around the top 3. We will send you the code for all 10 faces free + commission on sales via your affiliate link.',
    game: 'Roblox',
    gameType: 'roblox',
    platform: 'both',
    budget: 200,
    payoutType: 'fixed',
    minFollowers: 500,
    minAvgViewers: 30,
    duration: '1 stream (2-3 hrs)',
    scheduledDate: '2026-06-01T17:00:00Z',
    status: 'open',
    tags: ['ugc', 'limiteds', 'fashion', 'roblox'],
    applicants: 7,
    createdAt: '2026-05-18T14:00:00Z',
  },
  {
    id: 'g3',
    devId: 'd1',
    devName: 'NeonForge',
    devAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=neonforge',
    title: 'Launch Day Stream — PNEUMA Early Access',
    description:
      'PNEUMA is a body-horror metroidvania launching June 15th on Steam. We want a variety streamer to do a first-impressions playthrough. No script — just raw reactions. We will provide steam keys for you and your chat giveaways.',
    game: 'PNEUMA',
    gameType: 'steam',
    platform: 'twitch',
    budget: 350,
    payoutType: 'fixed',
    minFollowers: 2000,
    minAvgViewers: 100,
    duration: '3+ hours',
    scheduledDate: '2026-06-15T12:00:00Z',
    status: 'open',
    tags: ['steam', 'metroidvania', 'horror', 'launch'],
    applicants: 2,
    createdAt: '2026-05-15T09:00:00Z',
  },
  {
    id: 'g4',
    devId: 'd6',
    devName: 'ForgeFrame',
    devAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=forgeframe',
    title: 'Sponsored Segment — DARKWOOD Horror Game',
    description:
      'Promoting DARKWOOD from VoidInteractive. We need 3 streamers to play 60-90 min of this atmospheric horror game. Voiceover not required but preferred. Pre-written ad read available. High conversion game for horror audiences.',
    game: 'DARKWOOD',
    gameType: 'steam',
    platform: 'twitch',
    budget: 200,
    payoutType: 'fixed',
    minFollowers: 1000,
    duration: '90 minutes',
    scheduledDate: '2026-06-20T20:00:00Z',
    status: 'open',
    tags: ['horror', 'atmospheric', 'sponsored', 'steam'],
    applicants: 5,
    createdAt: '2026-05-17T11:00:00Z',
  },
  {
    id: 'g5',
    devId: 'd3',
    devName: 'BlockSmith',
    devAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=blocksmith',
    title: 'Minecraft SMP Server Launch Party',
    description:
      'New season of my survival SMP server launches June 5th. Looking for 2-3 Minecraft streamers to join the first day, build bases, and explore the custom terrain generation. Server has unique plugins — custom enchantments, player shops, and monthly events.',
    game: 'Minecraft',
    gameType: 'minecraft',
    platform: 'twitch',
    budget: 100,
    payoutType: 'per_hour',
    minFollowers: 500,
    minAvgViewers: 25,
    duration: '4 hours',
    scheduledDate: '2026-06-05T14:00:00Z',
    status: 'open',
    tags: ['minecraft', 'smp', 'survival', 'server-launch'],
    applicants: 6,
    createdAt: '2026-05-16T16:00:00Z',
  },
  {
    id: 'g6',
    devId: 'd8',
    devName: 'VoidInteractive',
    devAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=voidinteractive',
    title: 'HOLLOW VESSEL — Endgame Boss Rush Showcase',
    description:
      'HOLLOW VESSEL 1.0 is out. We want a skilled streamer to showcase the endgame boss rush (5 bosses back-to-back). This is for the hardcore audience. We need someone who can actually beat them — no frauds allowed.',
    game: 'HOLLOW VESSEL',
    gameType: 'steam',
    platform: 'twitch',
    budget: 500,
    payoutType: 'fixed',
    minFollowers: 3000,
    minAvgViewers: 150,
    duration: '2 hours',
    scheduledDate: '2026-06-25T19:00:00Z',
    status: 'open',
    tags: ['boss-rush', 'hardcore', 'steam', 'endgame'],
    applicants: 1,
    createdAt: '2026-05-19T08:00:00Z',
  },
  {
    id: 'g7',
    devId: 'd7',
    devName: 'RiftLabs',
    devAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=riftlabs',
    title: 'Play Our New Roblox Obby — SKY LADDER',
    description:
      'SKY LADDER is a next-gen obby with grapple hooks, anti-gravity zones, and 100 levels. We need a Roblox streamer to attempt a full completion on stream. First player to beat all 100 levels gets a $100 bonus.',
    game: 'SKY LADDER (Roblox)',
    gameType: 'roblox',
    platform: 'youtube',
    budget: 80,
    payoutType: 'fixed',
    duration: '1 stream',
    scheduledDate: '2026-06-08T15:00:00Z',
    status: 'open',
    tags: ['obby', 'roblox', 'challenge', 'speedrun'],
    applicants: 3,
    createdAt: '2026-05-17T13:00:00Z',
  },
  {
    id: 'g8',
    devId: 'd5',
    devName: 'CrystalCode',
    devAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=crystalcode',
    title: 'Indie Hidden Gem — ECHOES OF THE DEEP',
    description:
      'ECHOES OF THE DEEP is an underwater exploration game with a haunting soundtrack. I need a cozy/chill streamer to play through the first 2 chapters. No combat — pure atmosphere, story, and beautiful visuals.',
    game: 'ECHOES OF THE DEEP',
    gameType: 'steam',
    platform: 'both',
    budget: 120,
    payoutType: 'fixed',
    duration: '2-3 hours',
    scheduledDate: '2026-06-12T16:00:00Z',
    status: 'open',
    tags: ['cozy', 'exploration', 'indie', 'steam'],
    applicants: 8,
    createdAt: '2026-05-14T12:00:00Z',
  },
  {
    id: 'g9',
    devId: 'd10',
    devName: 'PhantomSeed',
    devAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=phantomseed',
    title: 'ROGUE FREQUENCY — Demo Weekend Stream',
    description:
      'ROGUE FREQUENCY is a tactical roguelike where your radio chatter affects enemy behavior. Demo drops June 1st for Steam Next Fest. Want 5 streamers to play the demo and give feedback. Priority to tactical/strategy streamers.',
    game: 'ROGUE FREQUENCY',
    gameType: 'steam',
    platform: 'twitch',
    budget: 75,
    payoutType: 'fixed',
    duration: '1-2 hours',
    scheduledDate: '2026-06-01T10:00:00Z',
    status: 'open',
    tags: ['demo', 'next-fest', 'tactical', 'roguelike'],
    applicants: 9,
    createdAt: '2026-05-16T09:00:00Z',
  },
  {
    id: 'g10',
    devId: 'd2',
    devName: 'PixelPunch',
    devAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=pixelpunch',
    title: 'Fortnite 1v1 Box Fight Tournament Host',
    description:
      'I host weekly Fortnite box fight tournaments and need a streamer to co-host/commentate. Prize pool of $100. You just need to stream your POV, hype the matches, and keep chat engaged.',
    game: 'Fortnite (Creative)',
    gameType: 'fortnite',
    platform: 'twitch',
    budget: 50,
    payoutType: 'fixed',
    minFollowers: 2000,
    minAvgViewers: 80,
    duration: '3 hours',
    scheduledDate: '2026-06-07T20:00:00Z',
    status: 'in_progress',
    tags: ['tournament', 'box-fight', 'competitive', 'host'],
    applicants: 3,
    createdAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'g11',
    devId: 'd9',
    devName: 'MojitoGames',
    devAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=mojitogames',
    title: 'FRUIT FUSION — Casual Mobile Playthrough',
    description:
      'FRUIT FUSION is a colorful match-3 with roguelike elements. Looking for casual/variety streamers to play on stream (mobile or emulator). Sweet visuals, relaxing vibes. Perfect for Just Chatting segments.',
    game: 'FRUIT FUSION',
    gameType: 'other',
    platform: 'both',
    budget: 30,
    payoutType: 'fixed',
    duration: '1 hour',
    scheduledDate: '2026-06-03T14:00:00Z',
    status: 'open',
    tags: ['casual', 'mobile', 'match-3', 'chill'],
    applicants: 2,
    createdAt: '2026-05-18T15:00:00Z',
  },
  {
    id: 'g12',
    devId: 'd3',
    devName: 'BlockSmith',
    devAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=blocksmith',
    title: 'Minecraft Minigames Showcase — 5 New Maps',
    description:
      'Just published 5 new Minecraft minigame maps: Spleef Deluxe, Parkour Paradise, BedWars Remix, SkyWars 2.0, and Dropper Infinite. Need a streamer to play through all 5 and rate them.',
    game: 'Minecraft',
    gameType: 'minecraft',
    platform: 'twitch',
    budget: 150,
    payoutType: 'per_viewer',
    minFollowers: 1000,
    minAvgViewers: 40,
    duration: '3 hours',
    scheduledDate: '2026-06-18T16:00:00Z',
    status: 'open',
    tags: ['minigames', 'minecraft', 'showcase', 'review'],
    applicants: 4,
    createdAt: '2026-05-19T07:00:00Z',
  },
  {
    id: 'g13',
    devId: 'd6',
    devName: 'ForgeFrame',
    devAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=forgeframe',
    title: 'Multi-Game Indie Bundle Stream',
    description:
      'We are bundling 5 indie Steam games for a summer sale. Need a streamer to play 20-30 min of each game in one stream. Games: GUNGEON, SLIME RANCHER 2, HADES II, HOLLOW VESSEL, PNEUMA. You get Steam keys for all 5.',
    game: 'Various',
    gameType: 'steam',
    platform: 'twitch',
    budget: 400,
    payoutType: 'fixed',
    minFollowers: 2500,
    minAvgViewers: 120,
    duration: '4 hours',
    scheduledDate: '2026-06-22T17:00:00Z',
    status: 'open',
    tags: ['bundle', 'indie', 'variety', 'steam'],
    applicants: 1,
    createdAt: '2026-05-20T10:00:00Z',
  },
  {
    id: 'g14',
    devId: 'd4',
    devName: 'UGC Studios',
    devAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=ugcstudios',
    title: 'Roblox Game Jam — Build With Us Live',
    description:
      'We are participating in the Roblox Game Jam (theme TBD). Want a dev streamer to co-build with us live on stream. We will cover the creative process, scripting, and modeling. Perfect for educational/behind-the-scenes content.',
    game: 'Roblox Studio',
    gameType: 'roblox',
    platform: 'both',
    budget: 250,
    payoutType: 'per_hour',
    minFollowers: 1500,
    minAvgViewers: 60,
    duration: '6 hours (split over 2 days)',
    scheduledDate: '2026-06-28T12:00:00Z',
    status: 'open',
    tags: ['game-jam', 'dev-stream', 'roblox', 'building'],
    applicants: 0,
    createdAt: '2026-05-20T09:00:00Z',
  },
  {
    id: 'g15',
    devId: 'd8',
    devName: 'VoidInteractive',
    devAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=voidinteractive',
    title: 'Completed: DARKWOOD Full Playthrough',
    description:
      'Full playthrough of DARKWOOD for release week. Streamer completed the game and provided a testimonial for the Steam page.',
    game: 'DARKWOOD',
    gameType: 'steam',
    platform: 'twitch',
    budget: 300,
    payoutType: 'fixed',
    duration: '6 hours',
    scheduledDate: '2026-05-10T18:00:00Z',
    status: 'completed',
    tags: ['horror', 'full-playthrough', 'steam', 'testimonial'],
    applicants: 2,
    createdAt: '2026-04-20T10:00:00Z',
  },
]

export const applications: Application[] = [
  {
    id: 'a1',
    gigId: 'g1',
    streamerId: 's5',
    streamerName: 'Vexxus',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=vexxus',
    streamerFollowers: 15400,
    streamerAvgViewers: 560,
    message:
      'I main Fortnite Creative maps. Neon Rooftops looks sick — I can test the movement tech and give you real feedback on pacing and spawns. I will clip the best moments for your marketing too.',
    status: 'pending',
    appliedAt: '2026-05-19T12:00:00Z',
  },
  {
    id: 'a2',
    gigId: 'g1',
    streamerId: 's8',
    streamerName: 'DriftKing',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=driftking',
    streamerFollowers: 6400,
    streamerAvgViewers: 220,
    message:
      'Box fighting is my specialty but I love exploring new creative maps too. Wall-running + ziplines sounds like a vibe. I can fill a 2-hour slot easily.',
    status: 'pending',
    appliedAt: '2026-05-19T14:30:00Z',
  },
  {
    id: 'a3',
    gigId: 'g2',
    streamerId: 's3',
    streamerName: 'KaiZen',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=kaizen',
    streamerFollowers: 8900,
    streamerAvgViewers: 320,
    message:
      'I already review UGC regularly on my streams. My community loves limited face reveals. Happy to feature all 10 and style outfits — this is literally my niche.',
    status: 'accepted',
    appliedAt: '2026-05-18T16:00:00Z',
  },
  {
    id: 'a4',
    gigId: 'g2',
    streamerId: 's10',
    streamerName: 'TurboShark',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=turboshark',
    streamerFollowers: 8700,
    streamerAvgViewers: 310,
    message:
      'Love Roblox limiteds. I can hype the drops and get my chat involved in voting for the best ones. Got an active community that loves this content.',
    status: 'pending',
    appliedAt: '2026-05-19T10:15:00Z',
  },
  {
    id: 'a5',
    gigId: 'g3',
    streamerId: 's1',
    streamerName: 'LunaRae',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=lunarae',
    streamerFollowers: 12800,
    streamerAvgViewers: 420,
    message:
      'I love metroidvanias and body horror aesthetic is my jam. PNEUMA looks like Hollow Knight meets Dead Space — I am so in. Can do launch day and stream for 4+ hours.',
    status: 'accepted',
    appliedAt: '2026-05-15T12:00:00Z',
  },
  {
    id: 'a6',
    gigId: 'g3',
    streamerId: 's9',
    streamerName: 'NovaGlow',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=novaglow',
    streamerFollowers: 5100,
    streamerAvgViewers: 190,
    message:
      'As an indie dev myself, I love supporting other indie devs. PNEUMA looks incredible. I can give it a thoughtful first-impressions playthrough.',
    status: 'pending',
    appliedAt: '2026-05-16T08:00:00Z',
  },
  {
    id: 'a7',
    gigId: 'g4',
    streamerId: 's6',
    streamerName: 'MellowMorph',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=mellowmorph',
    streamerFollowers: 3800,
    streamerAvgViewers: 145,
    message:
      'Horror is my wheelhouse. I played through DARKWOOD chapter 1 on my channel last month and my chat loved it. Happy to do a sponsored segment.',
    status: 'accepted',
    appliedAt: '2026-05-17T18:00:00Z',
  },
  {
    id: 'a8',
    gigId: 'g4',
    streamerId: 's4',
    streamerName: 'PixelKitten',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=pixelkitten',
    streamerFollowers: 7200,
    streamerAvgViewers: 250,
    message:
      'I do horror streams occasionally and DARKWOOD has been on my list! Would love to feature it as a sponsored segment. My audience is very engaged.',
    status: 'pending',
    appliedAt: '2026-05-18T09:00:00Z',
  },
  {
    id: 'a9',
    gigId: 'g5',
    streamerId: 's2',
    streamerName: 'Hexical',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=hexical',
    streamerFollowers: 5500,
    streamerAvgViewers: 180,
    message:
      'Minecraft SMPs are my favorite content to stream. Custom enchantments sound sick. I can commit to the full 4-hour launch and build something epic.',
    status: 'accepted',
    appliedAt: '2026-05-17T15:00:00Z',
  },
  {
    id: 'a10',
    gigId: 'g5',
    streamerId: 's7',
    streamerName: 'ByteBae',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=bytebae',
    streamerFollowers: 10200,
    streamerAvgViewers: 380,
    message:
      'Modded Minecraft and custom plugins are my passion. I would love to explore your SMP terrain and showcase the custom features. Can also help bug test!',
    status: 'pending',
    appliedAt: '2026-05-18T11:00:00Z',
  },
  {
    id: 'a11',
    gigId: 'g6',
    streamerId: 's1',
    streamerName: 'LunaRae',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=lunarae',
    streamerFollowers: 12800,
    streamerAvgViewers: 420,
    message:
      'I have already beaten HOLLOW VESSEL on my personal save. The boss rush will be no problem. I can do commentary on the lore and mechanics too.',
    status: 'pending',
    appliedAt: '2026-05-19T10:30:00Z',
  },
  {
    id: 'a12',
    gigId: 'g7',
    streamerId: 's10',
    streamerName: 'TurboShark',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=turboshark',
    streamerFollowers: 8700,
    streamerAvgViewers: 310,
    message:
      'Obbies are my guilty pleasure. Grapple hooks AND anti-gravity? I am going for that $100 bonus. Send me the link.',
    status: 'accepted',
    appliedAt: '2026-05-17T20:00:00Z',
  },
  {
    id: 'a13',
    gigId: 'g8',
    streamerId: 's4',
    streamerName: 'PixelKitten',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=pixelkitten',
    streamerFollowers: 7200,
    streamerAvgViewers: 250,
    message:
      'Underwater exploration + haunting soundtrack is my exact vibe. I do cozy Sunday streams and this would be perfect for that slot.',
    status: 'pending',
    appliedAt: '2026-05-15T14:00:00Z',
  },
  {
    id: 'a14',
    gigId: 'g8',
    streamerId: 's9',
    streamerName: 'NovaGlow',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=novaglow',
    streamerFollowers: 5100,
    streamerAvgViewers: 190,
    message:
      'As an indie game dev and cozy streamer, ECHOES OF THE DEEP is exactly the kind of game I love to feature. The art direction in the trailer is stunning.',
    status: 'accepted',
    appliedAt: '2026-05-14T20:00:00Z',
  },
  {
    id: 'a15',
    gigId: 'g9',
    streamerId: 's6',
    streamerName: 'MellowMorph',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=mellowmorph',
    streamerFollowers: 3800,
    streamerAvgViewers: 145,
    message:
      'Tactical roguelikes are my secret obsession. Radio chatter affecting enemy behavior is such a cool mechanic. I can definitely feature the demo.',
    status: 'pending',
    appliedAt: '2026-05-17T08:00:00Z',
  },
  {
    id: 'a16',
    gigId: 'g9',
    streamerId: 's5',
    streamerName: 'Vexxus',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=vexxus',
    streamerFollowers: 15400,
    streamerAvgViewers: 560,
    message:
      'I sometimes branch out from Fortnite for tactical games. ROGUE FREQUENCY sounds fresh. My chat would love the strategy elements.',
    status: 'rejected',
    appliedAt: '2026-05-16T10:00:00Z',
  },
  {
    id: 'a17',
    gigId: 'g11',
    streamerId: 's4',
    streamerName: 'PixelKitten',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=pixelkitten',
    streamerFollowers: 7200,
    streamerAvgViewers: 250,
    message:
      'FRUIT FUSION looks adorable. I do casual Fridays and this would be a perfect fit. Match-3 with roguelike elements is such a fun combo.',
    status: 'pending',
    appliedAt: '2026-05-18T18:00:00Z',
  },
  {
    id: 'a18',
    gigId: 'g12',
    streamerId: 's2',
    streamerName: 'Hexical',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=hexical',
    streamerFollowers: 5500,
    streamerAvgViewers: 180,
    message:
      'Parkour Paradise sounds right up my alley. I am known for Minecraft parkour content and would love to showcase all 5 maps. Dropper Infinite sounds wild.',
    status: 'pending',
    appliedAt: '2026-05-19T09:00:00Z',
  },
  {
    id: 'a19',
    gigId: 'g12',
    streamerId: 's7',
    streamerName: 'ByteBae',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=bytebae',
    streamerFollowers: 10200,
    streamerAvgViewers: 380,
    message:
      'I can do a full minigame marathon. BedWars Remix and SkyWars 2.0 are exactly what my community wants to see. Let me know if you want me to focus on any specific map.',
    status: 'pending',
    appliedAt: '2026-05-19T11:00:00Z',
  },
  {
    id: 'a20',
    gigId: 'g15',
    streamerId: 's6',
    streamerName: 'MellowMorph',
    streamerAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=mellowmorph',
    streamerFollowers: 3800,
    streamerAvgViewers: 145,
    message:
      'Completed full DARKWOOD playthrough on stream. Happy to provide a Steam testimonial and clips for your marketing.',
    status: 'completed',
    appliedAt: '2026-04-25T14:00:00Z',
  },
]