// ── Mock Data for Reference ──
// This file previously held a DataStore backed by localStorage.
// All data operations now go through src/lib/api-client.ts which
// calls the real API routes connected to the SQLite database.

import type { User, Gig, Application } from './types'

export const streamers: User[] = [
  {
    id: 's1',
    name: 'LunaRae',
    handle: 'lunarae',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=lunarae',
    role: 'streamer',
    bio: 'variety streamer | FPS queen | 25k hours in Fortnite | collab-friendly',
    joinedAt: '2023-08-14T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: 420,
    followers: 12800,
    totalGigsCompleted: 12,
    rating: 4.8,
    vibeScore: 92,
  },
  {
    id: 's2',
    name: 'Hexical',
    handle: 'hexytv',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=hexical',
    role: 'streamer',
    bio: 'Minecraft parkour god & indie game enjoyer. Building a community one block at a time.',
    joinedAt: '2024-01-22T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: 180,
    followers: 5500,
    totalGigsCompleted: 8,
    rating: 4.5,
    vibeScore: 78,
  },
  {
    id: 's3',
    name: 'KaiZen',
    handle: 'kaizentv',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=kaizen',
    role: 'streamer',
    bio: 'Roblox UGC reviewer & fashion guru. I find the dopest cosmetics so you dont have to.',
    joinedAt: '2024-03-10T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: 320,
    followers: 8900,
    totalGigsCompleted: 15,
    rating: 4.9,
    vibeScore: 95,
  },
  {
    id: 's4',
    name: 'PixelKitten',
    handle: 'pixelkitten',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=pixelkitten',
    role: 'streamer',
    bio: 'wholesome variety streamer | cozy games | FPS when the mood hits | 18+ chat',
    joinedAt: '2023-11-05T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: 250,
    followers: 7200,
    totalGigsCompleted: 6,
    rating: 4.6,
    vibeScore: 85,
  },
  {
    id: 's5',
    name: 'Vexxus',
    handle: 'vexxustv',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=vexxus',
    role: 'streamer',
    bio: 'Fortnite competitive grinder. Zone wars every day. Creative map tester.',
    joinedAt: '2024-05-18T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: 560,
    followers: 15400,
    totalGigsCompleted: 9,
    rating: 4.7,
    vibeScore: 88,
  },
  {
    id: 's6',
    name: 'MellowMorph',
    handle: 'mellowmorph',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=mellowmorph',
    role: 'streamer',
    bio: 'Late night vibes. Indie horror, puzzle games, and really bad puns.',
    joinedAt: '2024-02-14T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: 145,
    followers: 3800,
    totalGigsCompleted: 4,
    rating: 4.3,
    vibeScore: 72,
  },
  {
    id: 's7',
    name: 'ByteBae',
    handle: 'bytebae',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=bytebae',
    role: 'streamer',
    bio: 'tech + gaming | modded Minecraft | building insane redstone contraptions',
    joinedAt: '2023-09-30T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: 380,
    followers: 10200,
    totalGigsCompleted: 11,
    rating: 4.8,
    vibeScore: 90,
  },
  {
    id: 's8',
    name: 'DriftKing',
    handle: 'driftkingtv',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=driftking',
    role: 'streamer',
    bio: 'Fortnite box fighting phenom. Also speedrun any game you throw at me.',
    joinedAt: '2024-06-01T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: 220,
    followers: 6400,
    totalGigsCompleted: 5,
    rating: 4.4,
    vibeScore: 76,
  },
  {
    id: 's9',
    name: 'NovaGlow',
    handle: 'novaglow',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=novaglow',
    role: 'streamer',
    bio: 'art streamer | cozy game dev | I play my own games live | SUPPORT INDIE',
    joinedAt: '2024-04-12T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: 190,
    followers: 5100,
    totalGigsCompleted: 7,
    rating: 4.7,
    vibeScore: 83,
  },
  {
    id: 's10',
    name: 'TurboShark',
    handle: 'turboshark',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=turboshark',
    role: 'streamer',
    bio: 'I play literally anything. 1k hours in Roblox. Minecraft speedrunner. Bring it.',
    joinedAt: '2024-07-20T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: 310,
    followers: 8700,
    totalGigsCompleted: 3,
    rating: 4.2,
    vibeScore: 80,
  },
]

export const devs: User[] = [
  {
    id: 'd1',
    name: 'NeonForge',
    handle: 'neonforge',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=neonforge',
    role: 'dev',
    bio: 'indie game studio making weird & wonderful Steam games. 3 titles shipping this year.',
    joinedAt: '2024-01-08T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: true,
    totalGigsCompleted: 18,
    rating: 4.9,
    vibeScore: 94,
  },
  {
    id: 'd2',
    name: 'PixelPunch',
    handle: 'pixelpunch',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=pixelpunch',
    role: 'dev',
    bio: 'Fortnite Creative map designer. 12 published maps, 50M+ total plays.',
    joinedAt: '2024-02-19T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: false,
    totalGigsCompleted: 24,
    rating: 4.7,
    vibeScore: 89,
  },
  {
    id: 'd3',
    name: 'BlockSmith',
    handle: 'blocksmith',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=blocksmith',
    role: 'dev',
    bio: 'Minecraft server owner & plugin dev. Survival, minigames, and custom content.',
    joinedAt: '2024-03-05T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: false,
    totalGigsCompleted: 9,
    rating: 4.5,
    vibeScore: 81,
  },
  {
    id: 'd4',
    name: 'UGC Studios',
    handle: 'ugcstudios',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=ugcstudios',
    role: 'dev',
    bio: 'Roblox UGC creators. Limiteds, faces, accessories — if it looks fire, we made it.',
    joinedAt: '2024-04-01T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: true,
    totalGigsCompleted: 31,
    rating: 4.6,
    vibeScore: 87,
  },
  {
    id: 'd5',
    name: 'CrystalCode',
    handle: 'crystalcode',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=crystalcode',
    role: 'dev',
    bio: 'Solo dev. My game PNEUMA is coming to Steam Fall 2026. Body horror meets platformer.',
    joinedAt: '2024-06-15T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: true,
    totalGigsCompleted: 4,
    rating: 4.4,
    vibeScore: 79,
  },
  {
    id: 'd6',
    name: 'ForgeFrame',
    handle: 'forgeframe',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=forgeframe',
    role: 'dev',
    bio: 'Marketing agency for indie games. We connect devs with the right streamers.',
    joinedAt: '2023-12-10T10:00:00Z',
    twitchConnected: true,
    youtubeConnected: true,
    totalGigsCompleted: 47,
    rating: 4.8,
    vibeScore: 92,
  },
  {
    id: 'd7',
    name: 'RiftLabs',
    handle: 'riftlabs',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=riftlabs',
    role: 'dev',
    bio: 'We build Roblox experiences. 200M+ visits across our 7 games.',
    joinedAt: '2024-05-22T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: false,
    totalGigsCompleted: 14,
    rating: 4.3,
    vibeScore: 77,
  },
  {
    id: 'd8',
    name: 'VoidInteractive',
    handle: 'voidinteractive',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=voidinteractive',
    role: 'dev',
    bio: 'Horror game studio. DARKWOOD and HOLLOW VESSEL out now on Steam.',
    joinedAt: '2024-01-30T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: true,
    totalGigsCompleted: 11,
    rating: 4.9,
    vibeScore: 96,
  },
  {
    id: 'd9',
    name: 'MojitoGames',
    handle: 'mojitogames',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=mojitogames',
    role: 'dev',
    bio: 'Casual mobile & PC dev. Making colorful games with deep mechanics.',
    joinedAt: '2024-07-01T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: false,
    totalGigsCompleted: 6,
    rating: 4.1,
    vibeScore: 73,
  },
  {
    id: 'd10',
    name: 'PhantomSeed',
    handle: 'phantomseed',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=phantomseed',
    role: 'dev',
    bio: 'Upcoming tactical roguelike ROGUE FREQUENCY. Seeking variety streamers for launch.',
    joinedAt: '2024-08-10T10:00:00Z',
    twitchConnected: false,
    youtubeConnected: true,
    totalGigsCompleted: 2,
    rating: 4.0,
    vibeScore: 70,
  },
]

// The old DataStore (useSyncExternalStore, localStorage persistence) has been removed.
// All data operations now use the real API via src/lib/api-client.ts