import { PrismaClient } from "@prisma/client"
import { PrismaLibSql } from "@prisma/adapter-libsql"
import bcrypt from "bcryptjs"

const config = { url: process.env.DATABASE_URL ?? "file:./dev.db" }
const adapter = new PrismaLibSql(config)
const prisma = new PrismaClient({ adapter })

/* ────────── Mock Data (mirrors src/lib/data.ts) ────────── */

const streamerData = [
  {
    id: "s1",
    name: "LunaRae",
    handle: "lunarae",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=lunarae",
    role: "streamer",
    bio: "variety streamer | FPS queen | 25k hours in Fortnite | collab-friendly",
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: 420,
    followers: 12800,
    totalGigsCompleted: 12,
    rating: 4.8,
    vibeScore: 92,
    joinedAt: "2023-08-14T10:00:00Z",
  },
  {
    id: "s2",
    name: "Hexical",
    handle: "hexytv",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=hexical",
    role: "streamer",
    bio: "Minecraft parkour god & indie game enjoyer. Building a community one block at a time.",
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: 180,
    followers: 5500,
    totalGigsCompleted: 8,
    rating: 4.5,
    vibeScore: 78,
    joinedAt: "2024-01-22T10:00:00Z",
  },
  {
    id: "s3",
    name: "KaiZen",
    handle: "kaizentv",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=kaizen",
    role: "streamer",
    bio: "Roblox UGC reviewer & fashion guru. I find the dopest cosmetics so you dont have to.",
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: 320,
    followers: 8900,
    totalGigsCompleted: 15,
    rating: 4.9,
    vibeScore: 95,
    joinedAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "s4",
    name: "PixelKitten",
    handle: "pixelkitten",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=pixelkitten",
    role: "streamer",
    bio: "wholesome variety streamer | cozy games | FPS when the mood hits | 18+ chat",
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: 250,
    followers: 7200,
    totalGigsCompleted: 6,
    rating: 4.6,
    vibeScore: 85,
    joinedAt: "2023-11-05T10:00:00Z",
  },
  {
    id: "s5",
    name: "Vexxus",
    handle: "vexxustv",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=vexxus",
    role: "streamer",
    bio: "Fortnite competitive grinder. Zone wars every day. Creative map tester.",
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: 560,
    followers: 15400,
    totalGigsCompleted: 9,
    rating: 4.7,
    vibeScore: 88,
    joinedAt: "2024-05-18T10:00:00Z",
  },
  {
    id: "s6",
    name: "MellowMorph",
    handle: "mellowmorph",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=mellowmorph",
    role: "streamer",
    bio: "Late night vibes. Indie horror, puzzle games, and really bad puns.",
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: 145,
    followers: 3800,
    totalGigsCompleted: 4,
    rating: 4.3,
    vibeScore: 72,
    joinedAt: "2024-02-14T10:00:00Z",
  },
  {
    id: "s7",
    name: "ByteBae",
    handle: "bytebae",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=bytebae",
    role: "streamer",
    bio: "tech + gaming | modded Minecraft | building insane redstone contraptions",
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: 380,
    followers: 10200,
    totalGigsCompleted: 11,
    rating: 4.8,
    vibeScore: 90,
    joinedAt: "2023-09-30T10:00:00Z",
  },
  {
    id: "s8",
    name: "DriftKing",
    handle: "driftkingtv",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=driftking",
    role: "streamer",
    bio: "Fortnite box fighting phenom. Also speedrun any game you throw at me.",
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: 220,
    followers: 6400,
    totalGigsCompleted: 5,
    rating: 4.4,
    vibeScore: 76,
    joinedAt: "2024-06-01T10:00:00Z",
  },
  {
    id: "s9",
    name: "NovaGlow",
    handle: "novaglow",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=novaglow",
    role: "streamer",
    bio: "art streamer | cozy game dev | I play my own games live | SUPPORT INDIE",
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: 190,
    followers: 5100,
    totalGigsCompleted: 7,
    rating: 4.7,
    vibeScore: 83,
    joinedAt: "2024-04-12T10:00:00Z",
  },
  {
    id: "s10",
    name: "TurboShark",
    handle: "turboshark",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=turboshark",
    role: "streamer",
    bio: "I play literally anything. 1k hours in Roblox. Minecraft speedrunner. Bring it.",
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: 310,
    followers: 8700,
    totalGigsCompleted: 3,
    rating: 4.2,
    vibeScore: 80,
    joinedAt: "2024-07-20T10:00:00Z",
  },
]

const devData = [
  {
    id: "d1",
    name: "NeonForge",
    handle: "neonforge",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=neonforge",
    role: "dev",
    bio: "indie game studio making weird & wonderful Steam games. 3 titles shipping this year.",
    twitchConnected: false,
    youtubeConnected: true,
    avgViewers: null,
    followers: null,
    totalGigsCompleted: 18,
    rating: 4.9,
    vibeScore: 94,
    joinedAt: "2024-01-08T10:00:00Z",
  },
  {
    id: "d2",
    name: "PixelPunch",
    handle: "pixelpunch",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=pixelpunch",
    role: "dev",
    bio: "Fortnite Creative map designer. 12 published maps, 50M+ total plays.",
    twitchConnected: true,
    youtubeConnected: false,
    avgViewers: null,
    followers: null,
    totalGigsCompleted: 24,
    rating: 4.7,
    vibeScore: 89,
    joinedAt: "2024-02-19T10:00:00Z",
  },
  {
    id: "d3",
    name: "BlockSmith",
    handle: "blocksmith",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=blocksmith",
    role: "dev",
    bio: "Minecraft server owner & plugin dev. Survival, minigames, and custom content.",
    twitchConnected: false,
    youtubeConnected: false,
    avgViewers: null,
    followers: null,
    totalGigsCompleted: 9,
    rating: 4.5,
    vibeScore: 81,
    joinedAt: "2024-03-05T10:00:00Z",
  },
  {
    id: "d4",
    name: "UGC Studios",
    handle: "ugcstudios",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=ugcstudios",
    role: "dev",
    bio: "Roblox UGC creators. Limiteds, faces, accessories — if it looks fire, we made it.",
    twitchConnected: false,
    youtubeConnected: true,
    avgViewers: null,
    followers: null,
    totalGigsCompleted: 31,
    rating: 4.6,
    vibeScore: 87,
    joinedAt: "2024-04-01T10:00:00Z",
  },
  {
    id: "d5",
    name: "CrystalCode",
    handle: "crystalcode",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=crystalcode",
    role: "dev",
    bio: "Solo dev. My game PNEUMA is coming to Steam Fall 2026. Body horror meets platformer.",
    twitchConnected: false,
    youtubeConnected: true,
    avgViewers: null,
    followers: null,
    totalGigsCompleted: 4,
    rating: 4.4,
    vibeScore: 79,
    joinedAt: "2024-06-15T10:00:00Z",
  },
  {
    id: "d6",
    name: "ForgeFrame",
    handle: "forgeframe",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=forgeframe",
    role: "dev",
    bio: "Marketing agency for indie games. We connect devs with the right streamers.",
    twitchConnected: true,
    youtubeConnected: true,
    avgViewers: null,
    followers: null,
    totalGigsCompleted: 47,
    rating: 4.8,
    vibeScore: 92,
    joinedAt: "2023-12-10T10:00:00Z",
  },
  {
    id: "d7",
    name: "RiftLabs",
    handle: "riftlabs",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=riftlabs",
    role: "dev",
    bio: "We build Roblox experiences. 200M+ visits across our 7 games.",
    twitchConnected: false,
    youtubeConnected: false,
    avgViewers: null,
    followers: null,
    totalGigsCompleted: 14,
    rating: 4.3,
    vibeScore: 77,
    joinedAt: "2024-05-22T10:00:00Z",
  },
  {
    id: "d8",
    name: "VoidInteractive",
    handle: "voidinteractive",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=voidinteractive",
    role: "dev",
    bio: "Horror game studio. DARKWOOD and HOLLOW VESSEL out now on Steam.",
    twitchConnected: false,
    youtubeConnected: true,
    avgViewers: null,
    followers: null,
    totalGigsCompleted: 11,
    rating: 4.9,
    vibeScore: 96,
    joinedAt: "2024-01-30T10:00:00Z",
  },
  {
    id: "d9",
    name: "MojitoGames",
    handle: "mojitogames",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=mojitogames",
    role: "dev",
    bio: "Casual mobile & PC dev. Making colorful games with deep mechanics.",
    twitchConnected: false,
    youtubeConnected: false,
    avgViewers: null,
    followers: null,
    totalGigsCompleted: 6,
    rating: 4.1,
    vibeScore: 73,
    joinedAt: "2024-07-01T10:00:00Z",
  },
  {
    id: "d10",
    name: "PhantomSeed",
    handle: "phantomseed",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=phantomseed",
    role: "dev",
    bio: "Upcoming tactical roguelike ROGUE FREQUENCY. Seeking variety streamers for launch.",
    twitchConnected: false,
    youtubeConnected: true,
    avgViewers: null,
    followers: null,
    totalGigsCompleted: 2,
    rating: 4.0,
    vibeScore: 70,
    joinedAt: "2024-08-10T10:00:00Z",
  },
]

const gigData = [
  {
    id: "g1",
    devId: "d2",
    title: "Playtest & Showcase Neon Rooftops FFA Map",
    description:
      "I just dropped Neon Rooftops — a 32-player free-for-all map with wall-running, ziplines, and neon-glazed POIs. Need a streamer to run it for 2 hours, show off the movement mechanics, and give honest feedback. Bonus if you clip the best moments for TikTok.",
    game: "Fortnite (Creative)",
    gameType: "fortnite",
    platform: "twitch",
    budget: 150,
    payoutType: "fixed",
    minFollowers: 1000,
    minAvgViewers: 50,
    duration: "2 hours",
    scheduledDate: "2026-06-10T18:00:00Z",
    status: "open",
    tags: ["creative", "ffa", "new-map", "gameplay"],
    applicants: 4,
    createdAt: "2026-05-19T10:00:00Z",
  },
  {
    id: "g2",
    devId: "d4",
    title: "Rate Our New Roblox Limited Face Collection",
    description:
      "Dropping 10 new limited faces next week. Want a streamer to go through them live, rate them, and style outfits around the top 3. We will send you the code for all 10 faces free + commission on sales via your affiliate link.",
    game: "Roblox",
    gameType: "roblox",
    platform: "both",
    budget: 200,
    payoutType: "fixed",
    minFollowers: 500,
    minAvgViewers: 30,
    duration: "1 stream (2-3 hrs)",
    scheduledDate: "2026-06-01T17:00:00Z",
    status: "open",
    tags: ["ugc", "limiteds", "fashion", "roblox"],
    applicants: 7,
    createdAt: "2026-05-18T14:00:00Z",
  },
  {
    id: "g3",
    devId: "d1",
    title: "Launch Day Stream — PNEUMA Early Access",
    description:
      "PNEUMA is a body-horror metroidvania launching June 15th on Steam. We want a variety streamer to do a first-impressions playthrough. No script — just raw reactions. We will provide steam keys for you and your chat giveaways.",
    game: "PNEUMA",
    gameType: "steam",
    platform: "twitch",
    budget: 350,
    payoutType: "fixed",
    minFollowers: 2000,
    minAvgViewers: 100,
    duration: "3+ hours",
    scheduledDate: "2026-06-15T12:00:00Z",
    status: "open",
    tags: ["steam", "metroidvania", "horror", "launch"],
    applicants: 2,
    createdAt: "2026-05-15T09:00:00Z",
  },
  {
    id: "g4",
    devId: "d6",
    title: "Sponsored Segment — DARKWOOD Horror Game",
    description:
      "Promoting DARKWOOD from VoidInteractive. We need 3 streamers to play 60-90 min of this atmospheric horror game. Voiceover not required but preferred. Pre-written ad read available. High conversion game for horror audiences.",
    game: "DARKWOOD",
    gameType: "steam",
    platform: "twitch",
    budget: 200,
    payoutType: "fixed",
    minFollowers: 1000,
    duration: "90 minutes",
    scheduledDate: "2026-06-20T20:00:00Z",
    status: "open",
    tags: ["horror", "atmospheric", "sponsored", "steam"],
    applicants: 5,
    createdAt: "2026-05-17T11:00:00Z",
  },
  {
    id: "g5",
    devId: "d3",
    title: "Minecraft SMP Server Launch Party",
    description:
      "New season of my survival SMP server launches June 5th. Looking for 2-3 Minecraft streamers to join the first day, build bases, and explore the custom terrain generation. Server has unique plugins — custom enchantments, player shops, and monthly events.",
    game: "Minecraft",
    gameType: "minecraft",
    platform: "twitch",
    budget: 100,
    payoutType: "per_hour",
    minFollowers: 500,
    minAvgViewers: 25,
    duration: "4 hours",
    scheduledDate: "2026-06-05T14:00:00Z",
    status: "open",
    tags: ["minecraft", "smp", "survival", "server-launch"],
    applicants: 6,
    createdAt: "2026-05-16T16:00:00Z",
  },
  {
    id: "g6",
    devId: "d8",
    title: "HOLLOW VESSEL — Endgame Boss Rush Showcase",
    description:
      "HOLLOW VESSEL 1.0 is out. We want a skilled streamer to showcase the endgame boss rush (5 bosses back-to-back). This is for the hardcore audience. We need someone who can actually beat them — no frauds allowed.",
    game: "HOLLOW VESSEL",
    gameType: "steam",
    platform: "twitch",
    budget: 500,
    payoutType: "fixed",
    minFollowers: 3000,
    minAvgViewers: 150,
    duration: "2 hours",
    scheduledDate: "2026-06-25T19:00:00Z",
    status: "open",
    tags: ["boss-rush", "hardcore", "steam", "endgame"],
    applicants: 1,
    createdAt: "2026-05-19T08:00:00Z",
  },
  {
    id: "g7",
    devId: "d7",
    title: "Play Our New Roblox Obby — SKY LADDER",
    description:
      "SKY LADDER is a next-gen obby with grapple hooks, anti-gravity zones, and 100 levels. We need a Roblox streamer to attempt a full completion on stream. First player to beat all 100 levels gets a $100 bonus.",
    game: "SKY LADDER (Roblox)",
    gameType: "roblox",
    platform: "youtube",
    budget: 80,
    payoutType: "fixed",
    duration: "1 stream",
    scheduledDate: "2026-06-08T15:00:00Z",
    status: "open",
    tags: ["obby", "roblox", "challenge", "speedrun"],
    applicants: 3,
    createdAt: "2026-05-17T13:00:00Z",
  },
  {
    id: "g8",
    devId: "d5",
    title: "Indie Hidden Gem — ECHOES OF THE DEEP",
    description:
      "ECHOES OF THE DEEP is an underwater exploration game with a haunting soundtrack. I need a cozy/chill streamer to play through the first 2 chapters. No combat — pure atmosphere, story, and beautiful visuals.",
    game: "ECHOES OF THE DEEP",
    gameType: "steam",
    platform: "both",
    budget: 120,
    payoutType: "fixed",
    duration: "2-3 hours",
    scheduledDate: "2026-06-12T16:00:00Z",
    status: "open",
    tags: ["cozy", "exploration", "indie", "steam"],
    applicants: 8,
    createdAt: "2026-05-14T12:00:00Z",
  },
  {
    id: "g9",
    devId: "d10",
    title: "ROGUE FREQUENCY — Demo Weekend Stream",
    description:
      "ROGUE FREQUENCY is a tactical roguelike where your radio chatter affects enemy behavior. Demo drops June 1st for Steam Next Fest. Want 5 streamers to play the demo and give feedback. Priority to tactical/strategy streamers.",
    game: "ROGUE FREQUENCY",
    gameType: "steam",
    platform: "twitch",
    budget: 75,
    payoutType: "fixed",
    duration: "1-2 hours",
    scheduledDate: "2026-06-01T10:00:00Z",
    status: "open",
    tags: ["demo", "next-fest", "tactical", "roguelike"],
    applicants: 9,
    createdAt: "2026-05-16T09:00:00Z",
  },
  {
    id: "g10",
    devId: "d2",
    title: "Fortnite 1v1 Box Fight Tournament Host",
    description:
      "I host weekly Fortnite box fight tournaments and need a streamer to co-host/commentate. Prize pool of $100. You just need to stream your POV, hype the matches, and keep chat engaged.",
    game: "Fortnite (Creative)",
    gameType: "fortnite",
    platform: "twitch",
    budget: 50,
    payoutType: "fixed",
    minFollowers: 2000,
    minAvgViewers: 80,
    duration: "3 hours",
    scheduledDate: "2026-06-07T20:00:00Z",
    status: "in_progress",
    tags: ["tournament", "box-fight", "competitive", "host"],
    applicants: 3,
    createdAt: "2026-05-10T10:00:00Z",
  },
  {
    id: "g11",
    devId: "d9",
    title: "FRUIT FUSION — Casual Mobile Playthrough",
    description:
      "FRUIT FUSION is a colorful match-3 with roguelike elements. Looking for casual/variety streamers to play on stream (mobile or emulator). Sweet visuals, relaxing vibes. Perfect for Just Chatting segments.",
    game: "FRUIT FUSION",
    gameType: "other",
    platform: "both",
    budget: 30,
    payoutType: "fixed",
    duration: "1 hour",
    scheduledDate: "2026-06-03T14:00:00Z",
    status: "open",
    tags: ["casual", "mobile", "match-3", "chill"],
    applicants: 2,
    createdAt: "2026-05-18T15:00:00Z",
  },
  {
    id: "g12",
    devId: "d3",
    title: "Minecraft Minigames Showcase — 5 New Maps",
    description:
      "Just published 5 new Minecraft minigame maps: Spleef Deluxe, Parkour Paradise, BedWars Remix, SkyWars 2.0, and Dropper Infinite. Need a streamer to play through all 5 and rate them.",
    game: "Minecraft",
    gameType: "minecraft",
    platform: "twitch",
    budget: 150,
    payoutType: "per_viewer",
    minFollowers: 1000,
    minAvgViewers: 40,
    duration: "3 hours",
    scheduledDate: "2026-06-18T16:00:00Z",
    status: "open",
    tags: ["minigames", "minecraft", "showcase", "review"],
    applicants: 4,
    createdAt: "2026-05-19T07:00:00Z",
  },
  {
    id: "g13",
    devId: "d6",
    title: "Multi-Game Indie Bundle Stream",
    description:
      "We are bundling 5 indie Steam games for a summer sale. Need a streamer to play 20-30 min of each game in one stream. Games: GUNGEON, SLIME RANCHER 2, HADES II, HOLLOW VESSEL, PNEUMA. You get Steam keys for all 5.",
    game: "Various",
    gameType: "steam",
    platform: "twitch",
    budget: 400,
    payoutType: "fixed",
    minFollowers: 2500,
    minAvgViewers: 120,
    duration: "4 hours",
    scheduledDate: "2026-06-22T17:00:00Z",
    status: "open",
    tags: ["bundle", "indie", "variety", "steam"],
    applicants: 1,
    createdAt: "2026-05-20T10:00:00Z",
  },
  {
    id: "g14",
    devId: "d4",
    title: "Roblox Game Jam — Build With Us Live",
    description:
      "We are participating in the Roblox Game Jam (theme TBD). Want a dev streamer to co-build with us live on stream. We will cover the creative process, scripting, and modeling. Perfect for educational/behind-the-scenes content.",
    game: "Roblox Studio",
    gameType: "roblox",
    platform: "both",
    budget: 250,
    payoutType: "per_hour",
    minFollowers: 1500,
    minAvgViewers: 60,
    duration: "6 hours (split over 2 days)",
    scheduledDate: "2026-06-28T12:00:00Z",
    status: "open",
    tags: ["game-jam", "dev-stream", "roblox", "building"],
    applicants: 0,
    createdAt: "2026-05-20T09:00:00Z",
  },
  {
    id: "g15",
    devId: "d8",
    title: "Completed: DARKWOOD Full Playthrough",
    description:
      "Full playthrough of DARKWOOD for release week. Streamer completed the game and provided a testimonial for the Steam page.",
    game: "DARKWOOD",
    gameType: "steam",
    platform: "twitch",
    budget: 300,
    payoutType: "fixed",
    duration: "6 hours",
    scheduledDate: "2026-05-10T18:00:00Z",
    status: "completed",
    tags: ["horror", "full-playthrough", "steam", "testimonial"],
    applicants: 2,
    createdAt: "2026-04-20T10:00:00Z",
  },
]

const appData = [
  {
    id: "a1",
    gigId: "g1",
    streamerId: "s5",
    message:
      "I main Fortnite Creative maps. Neon Rooftops looks sick — I can test the movement tech and give you real feedback on pacing and spawns. I will clip the best moments for your marketing too.",
    status: "pending",
    appliedAt: "2026-05-19T12:00:00Z",
  },
  {
    id: "a2",
    gigId: "g1",
    streamerId: "s8",
    message:
      "Box fighting is my specialty but I love exploring new creative maps too. Wall-running + ziplines sounds like a vibe. I can fill a 2-hour slot easily.",
    status: "pending",
    appliedAt: "2026-05-19T14:30:00Z",
  },
  {
    id: "a3",
    gigId: "g2",
    streamerId: "s3",
    message:
      "I already review UGC regularly on my streams. My community loves limited face reveals. Happy to feature all 10 and style outfits — this is literally my niche.",
    status: "accepted",
    appliedAt: "2026-05-18T16:00:00Z",
  },
  {
    id: "a4",
    gigId: "g2",
    streamerId: "s10",
    message:
      "Love Roblox limiteds. I can hype the drops and get my chat involved in voting for the best ones. Got an active community that loves this content.",
    status: "pending",
    appliedAt: "2026-05-19T10:15:00Z",
  },
  {
    id: "a5",
    gigId: "g3",
    streamerId: "s1",
    message:
      "I love metroidvanias and body horror aesthetic is my jam. PNEUMA looks like Hollow Knight meets Dead Space — I am so in. Can do launch day and stream for 4+ hours.",
    status: "accepted",
    appliedAt: "2026-05-15T12:00:00Z",
  },
  {
    id: "a6",
    gigId: "g3",
    streamerId: "s9",
    message:
      "As an indie dev myself, I love supporting other indie devs. PNEUMA looks incredible. I can give it a thoughtful first-impressions playthrough.",
    status: "pending",
    appliedAt: "2026-05-16T08:00:00Z",
  },
  {
    id: "a7",
    gigId: "g4",
    streamerId: "s6",
    message:
      "Horror is my wheelhouse. I played through DARKWOOD chapter 1 on my channel last month and my chat loved it. Happy to do a sponsored segment.",
    status: "accepted",
    appliedAt: "2026-05-17T18:00:00Z",
  },
  {
    id: "a8",
    gigId: "g4",
    streamerId: "s4",
    message:
      "Horror games are my comfort zone lol. DARKWOOD has been on my list forever. Would love to do a sponsored segment and give it a genuine playthrough.",
    status: "pending",
    appliedAt: "2026-05-18T09:00:00Z",
  },
  {
    id: "a9",
    gigId: "g5",
    streamerId: "s2",
    message:
      "Minecraft SMP is my entire brand. I play on 3 servers already and my community loves base tours and progression content. I can bring the hype for your launch day!",
    status: "pending",
    appliedAt: "2026-05-17T14:00:00Z",
  },
  {
    id: "a10",
    gigId: "g5",
    streamerId: "s7",
    message:
      "Custom enchantments AND player shops? This SMP sounds next level. I specialize in modded/plugin-heavy Minecraft content. Can do a full 4-hour first-day stream.",
    status: "pending",
    appliedAt: "2026-05-18T11:30:00Z",
  },
  {
    id: "a11",
    gigId: "g6",
    streamerId: "s1",
    message:
      "I love a challenge. 5 bosses back-to-back sounds insane. I have completed HOLLOW VESSEL on my own time — I can absolutely beat the boss rush on stream.",
    status: "pending",
    appliedAt: "2026-05-19T15:45:00Z",
  },
  {
    id: "a12",
    gigId: "g7",
    streamerId: "s3",
    message:
      "SKY LADDER looks sick. Grapple hooks + anti-gravity is a fresh take on obbys. I will go for 100 levels — that $100 bonus is mine.",
    status: "pending",
    appliedAt: "2026-05-18T16:20:00Z",
  },
  {
    id: "a13",
    gigId: "g8",
    streamerId: "s4",
    message:
      "This sounds like my exact vibe. Underwater exploration with a haunting soundtrack? Perfect for a cozy/chill stream. I will fully immerse myself in the first 2 chapters.",
    status: "pending",
    appliedAt: "2026-05-15T14:00:00Z",
  },
  {
    id: "a14",
    gigId: "g8",
    streamerId: "s9",
    message:
      "Exploration games with deep atmosphere are my favorite content to make. Would love to showcase this indie title — the screenshots look gorgeous.",
    status: "pending",
    appliedAt: "2026-05-16T10:30:00Z",
  },
  {
    id: "a15",
    gigId: "g10",
    streamerId: "s8",
    message:
      "Box fighting is literally all I do. I can commentate and hype the matches while holding my own. This is the perfect gig for me.",
    status: "accepted",
    appliedAt: "2026-05-11T09:00:00Z",
  },
  {
    id: "a16",
    gigId: "g10",
    streamerId: "s5",
    message:
      "Tournament hosting with 1v1 box fights? This is content gold. I can co-host, keep the energy high, and make sure the stream is entertaining even between matches.",
    status: "pending",
    appliedAt: "2026-05-12T12:00:00Z",
  },
  {
    id: "a17",
    gigId: "g4",
    streamerId: "s4",
    message:
      "Horror is surprisingly one of my most-requested categories. I would love to do a sponsored segment for DARKWOOD.",
    status: "completed",
    appliedAt: "2026-05-17T20:00:00Z",
  },
]

async function seed() {
  console.log("🧹 Clearing existing data...")
  await prisma.application.deleteMany()
  await prisma.gig.deleteMany()
  await prisma.session.deleteMany()
  await prisma.account.deleteMany()
  await prisma.user.deleteMany()

  console.log("👤 Creating users...")
  const passwordHash = await bcrypt.hash("password123", 10)
  const allUsers = [...streamerData, ...devData]

  for (const u of allUsers) {
    await prisma.user.create({
      data: {
        id: u.id,
        name: u.name,
        handle: u.handle,
        email: `${u.handle}@vibe.dev`,
        hashedPassword: passwordHash,
        image: u.avatar,
        role: u.role,
        bio: u.bio,
        twitchConnected: u.twitchConnected,
        youtubeConnected: u.youtubeConnected,
        twitchUsername: u.twitchConnected ? u.handle : null,
        youtubeChannelId: u.youtubeConnected ? `yt_${u.handle}` : null,
        avgViewers: u.avgViewers,
        followers: u.followers,
        totalGigsCompleted: u.totalGigsCompleted,
        vibeScore: u.vibeScore,
        rating: u.rating,
        createdAt: new Date(u.joinedAt),
      },
    })
  }
  console.log(`✅ Created ${allUsers.length} users`)

  console.log("🎮 Creating gigs...")
  for (const g of gigData) {
    await prisma.gig.create({
      data: {
        id: g.id,
        devId: g.devId,
        title: g.title,
        description: g.description,
        game: g.game,
        gameType: g.gameType,
        platform: g.platform,
        budget: g.budget,
        payoutType: g.payoutType,
        minFollowers: g.minFollowers ?? null,
        minAvgViewers: g.minAvgViewers ?? null,
        duration: g.duration,
        scheduledDate: new Date(g.scheduledDate),
        status: g.status,
        tags: JSON.stringify(g.tags),
        applicants: g.applicants,
        createdAt: new Date(g.createdAt),
      },
    })
  }
  console.log(`✅ Created ${gigData.length} gigs`)

  console.log("📋 Creating applications...")
  let appsCreated = 0
  for (const a of appData) {
    try {
      await prisma.application.create({
        data: {
          id: a.id,
          gigId: a.gigId,
          streamerId: a.streamerId,
          message: a.message,
          status: a.status,
          appliedAt: new Date(a.appliedAt),
        },
      })
      appsCreated++
    } catch (e: any) {
      if (e?.code === "P2002") {
        console.log(`  ⚠️ Skipping duplicate application ${a.id} (gig ${a.gigId}, streamer ${a.streamerId})`)
      } else {
        throw e
      }
    }
  }
  console.log(`✅ Created ${appsCreated} applications (${appData.length - appsCreated} duplicates skipped)`)

  console.log("🎉 Seed complete!")
}

export { seed }

seed()
  .catch((e) => {
    console.error("❌ Seed failed:", e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())